version: '3'
networks:
  mynet:
services:
  giglabo-file-uploading-minio:
    image: minio/minio
    container_name: giglabo-file-uploading-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER=on
      - MINIO_CORS_ALLOW_ORIGIN=https://dev.file-uploader.giglabo.com,http://localhost:3000,http://localhost:3001,*
      - MINIO_CORS_ALLOW_METHODS=GET,PUT,POST,DELETE,HEAD,OPTIONS,PATCH
      - MINIO_CORS_ALLOW_HEADERS=*
      - MINIO_CORS_EXPOSE_HEADERS=ETag,Content-Length,Content-Type,X-Amz-*
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    #      - giglabo_file_uploading_minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      mynet:
  giglabo-file-uploading-postgres:
    image: postgres:15.12
    container_name: giglabo-file-uploading-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - giglabo_file_uploading_postgres_data:/var/lib/postgresql/data
    networks:
      mynet:
  dev-nginx:
    container_name: dev-nginx
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    volumes:
      - ./logs:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./includes:/etc/nginx/includes
      - ./dhparam.pem:/etc/nginx/dhparam.pem
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./files:/www/files
      - ./cert:/cert
      - ../dist/apps/demo-nextjs/.next/static:/www/demo-nextjs/static
      - ../apps/demo-nextjs/public:/www/demo-nextjs/public
    ports:
      - 443:443
      - 80:80
      - 81:81
      - 82:82
    extra_hosts:
      - "public-service:${IP_ADDR_PUBLIC}"
      - "main-service:${IP_ADDR_PUBLIC}"
    networks:
      mynet:
volumes:
  #  giglabo_file_uploading_minio_data:
  giglabo_file_uploading_postgres_data:
