FROM node:20.19.0-alpine3.20 as build0
RUN apk add --no-cache g++ make python3

WORKDIR /app
ENV NODE_ENV=production
COPY apps/demo-nextjs/package.json package-lock.json postinstall.js ./
RUN npm install -g npm@6
RUN npm ci  --no-audit --omit=dev --force


# run
FROM node:20.19.0-alpine3.20
WORKDIR /app

ENV NODE_ENV=production

#RUN addgroup --system --gid 1000 nextjs
#RUN adduser --system --uid 1000 nextjs

COPY --from=build0  --chown=nextjs:nodejs /app/node_modules /app/node_modules

#USER nextjs
ENV HOSTNAME="0.0.0.0"
ENTRYPOINT ["node"]

EXPOSE ${PORT}
